create table "public"."from_local" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "more_stuff" text
);


alter table "public"."from_local" enable row level security;

CREATE UNIQUE INDEX from_local_pkey ON public.from_local USING btree (id);

alter table "public"."from_local" add constraint "from_local_pkey" PRIMARY KEY using index "from_local_pkey";


